### ISSUE TITLE
an error with jsDoc

### ISSUE THREAD

**Issue by dtracers** [jscs-dev/jscs-jsdoc#198]
```
internalError: Error running rule jsDoc: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
TypeError: Cannot read property 'offset' of undefined
    at Object.enforceExistence (D:\workspace\Srl-SketchSurface\node_modules\jscs-jsdoc\lib\rules\validate-jsdoc\enforce-existence.js:116:65)
    at D:\workspace\Srl-SketchSurface\node_modules\jscs-jsdoc\lib\rules\validate-jsdoc.js:128:27
    at Array.forEach (native)
    at Object.<anonymous> (D:\workspace\Srl-SketchSurface\node_modules\jscs-jsdoc\lib\rules\validate-jsdoc.js:127:32)
    at Array.forEach (native)
    at Object.JsFile.iterateNodesByType (D:\workspace\Srl-SketchSurface\node_modules\jscs\lib\js-file.js:331:42)
    at D:\workspace\Srl-SketchSurface\node_modules\jscs-jsdoc\lib\rules\validate-jsdoc.js:120:18
    at Array.forEach (native)
    at Object.module.exports.check (D:\workspace\Srl-SketchSurface\node_modules\jscs-jsdoc\lib\rules\validate-jsdoc.js:112:29)
    at [object Object].<anonymous> (D:\workspace\Srl-SketchSurface\node_modules\jscs\lib\string-checker.js:189:22)
    at Array.forEach (native)
    at [object Object].StringChecker._checkJsFile (D:\workspace\Srl-SketchSurface\node_modules\jscs\lib\string-checker.js:185:31)
    at [object Object].StringChecker.checkString (D:\workspace\Srl-SketchSurface\node_modules\jscs\lib\string-checker.js:92:14)
    at [object Object].<anonymous> (D:\workspace\Srl-SketchSurface\node_modules\jscs\lib\checker.js:56:21)
    at Array.<anonymous> (D:\workspace\Srl-SketchSurface\node_modules\vow\lib\vow.js:712:39)
    at Immediate.callFns [as _onImmediate] (D:\workspace\Srl-SketchSurface\node_modules\vow\lib\vow.js:23:35)
    at processImmediate [as _immediateCallback] (timers.js:383:17) at Gruntfile.js :
     1 |// jscs:disable jsDoc
--------^
     2 |
     3 |var rewriteRulesSnippet = require('grunt-connect-rewrite/lib/utils').rewriteRequest;
```

This is running on my grunt file. I am using verison 3.0.0

**Comment by numblock** [comment]
For what it's worth, I got this error when one of my doc comments ended in: `**/` instead of `*/`
